### ISSUE TITLE
FlowForms Core - Deploy a package. Setup Github actions

### ISSUE THREAD

**Issue by hrodrick** [rootstrap/FlowForms#10]
### Requirements
 * Configure a CI CD pipeline using GitHub Actions to build and run tests on push
 * Configure a CI CD pipeline using GitHub Actions to builld, run tests and deploy Flow form core's packages to make them available to users, following a x.x.x version pattern. Starting at 0.0.1.
 * We should be able to trigger the pipeline using a git **tag** like "v0.0.1"
 * Release the first package 🥳 
 * All modules should be released under the same version, so it's easy to import and manage them.

### Notes 
 * Depends on #6 as there are all the FF's core features (including current tests)
 * Current available test command for FF's core is `./gradlew FlowForms-Core:jvmTest`

### tasks
- [x] Setup unit tests execution using github actions, required to merge Pull requests
- [x] Create a release and deploy a package to a remote artifact repository.
- [x] Add a badge with the last release deployed.
- [ ] Configurate auto deploys based on releases. (should be started when having an android extensions version ready)

**Comment by hrodrick** [comment]
We can consider this point :
`Configurate auto deploys based on releases. (should be started when having an android extensions version ready)` 
as wont-fix because with Jitpack there is no need for such setup. We just need to create a github release (with its tag) and click on the "get" button in the Jitpack. It automatically updates the Version badge.
